import { extendTailwindMerge } from 'tailwind-merge';

export const twMergeCustom = extendTailwindMerge({
  extend: {
    classGroups: {
      'font-size': [
        {
          text: [
            'sm',
            'md',
            'lg',
            'xl',
            'xxl',
            'xxxl',
            '3xl',
            '2xl',
            '1xl',
            '0xl',
            'ls',
            'l',
            'm',
            'sh',
            's',
            'sm-3xl',
            'sm-2xl',
            'sm-1xl',
            'sm-ls',
            'sm-l',
            'sm-m',
            'sm-s',
            'sm-3xl-vw',
            'sm-2xl-vw',
            'sm-1xl-vw',
            'sm-ls-vw',
            'sm-l-vw',
            'sm-m-vw',
            'sm-s-vw',
          ],
        },
      ],
    },
    theme: {
      borderRadius: [
        'inherit',
        'none',
        'sm',
        'lg',
        'full',
        'xl-1',
        'xl-2',
        'xl-3',
        'xl-4',
        'xl-5',
        'xl-6',
        'sm-1-vw',
        'sm-2-vw',
        'sm-3-vw',
        'sm-4-vw',
        'sm-6-vw',
      ],
      colors: [
        'primary',
        'secondary',
        'white',
        'gray-extra-light',
        'gray-light',
        'gray',
        'bright-green',
        'gray-warm',
        'gray-dark',
        'black',
        'green',
        'violet-light',
        'violet',
        'violet-dark',
        'red',
        'red-second',
        'pink',
        'white-80',
        'black-05',
        'black-08',
      ],
      spacing: [
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        'sm-1-vw',
        'sm-2-vw',
        'sm-3-vw',
        'sm-4-vw',
        'sm-5-vw',
        'sm-6-vw',
        'sm-7-vw',
        'sm-8-vw',
        'sm-9-vw',
        'sm-10-vw',
        'sm-11-vw',
        'sm-12-vw',
        'sm-13-vw',
        'sm-14-vw',
        'sm-15-vw',
        'sm-16-vw',
        'sm-17-vw',
        'sm-18-vw',
      ],
    },
  },
});
